"""Initial migration

Revision ID: 69ca8274b2df
Revises: 
Create Date: 2026-04-28 11:06:54.216304

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "69ca8274b2df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("outbox",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("aggregate_id", sa.UUID(), nullable=False),
    sa.Column("event_type", sa.String(length=64), nullable=False),
    sa.Column("payload", sa.JSON(), nullable=False),
    sa.Column("idempotency_key", sa.UUID(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index("ix_outbox_unprocessed", "outbox", ["processed_at", "created_at"], unique=False)
    op.create_table("payments",
    sa.Column("id", sa.UUID(), nullable=False),
    sa.Column("idempotency_key", sa.UUID(), nullable=False),
    sa.Column("amount", sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column("currency", sa.String(length=3), nullable=False),
    sa.Column("webhook", sa.String(length=255), nullable=False),
    sa.Column("description", sa.String(length=255), nullable=True),
    sa.Column("meta_data", sa.JSON(), nullable=True),
    sa.Column("status", sa.String(length=30), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("idempotency_key")
    )
    op.create_index("idx_payments_status_created", "payments", ["status", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_payments_status_created", table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_outbox_unprocessed", table_name="outbox")
    op.drop_table("outbox")
    # ### end Alembic commands ###
